"use client";

// App-wide UI internationalisation. The whole interface (nav, onboarding,
// buttons, labels) renders in the user's language — resolved from the device
// locale the moment dotit opens, or the user's saved preference. Strings are
// keyed by their English text; t() returns the translation for the active
// locale, or the English original as a safe fallback (so the app never breaks
// even if a string is missing). Translations live in lib/i18n/translations.json
// (generated by i18n/translate.py for all 100 languages).

import { createContext, useContext, useEffect, ReactNode } from "react";
import { languageByCode } from "./languages";
import translations from "./i18n/translations.json";

type Dict = Record<string, string>;
const ALL = translations as Record<string, Dict>;

type I18n = {
  locale: string;
  rtl: boolean;
  t: (s: string, vars?: Record<string, string | number>) => string;
};

const I18nCtx = createContext<I18n>({ locale: "en-US", rtl: false, t: (s) => s });

export function I18nProvider({ locale, children }: { locale: string; children: ReactNode }) {
  const dict = ALL[locale] || ALL[locale?.split("-")[0]] || {};
  const rtl = Boolean(languageByCode(locale)?.rtl);

  // Flip the whole document for RTL scripts + set lang for a11y.
  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.dir = rtl ? "rtl" : "ltr";
      document.documentElement.lang = locale || "en-US";
    }
  }, [locale, rtl]);

  function t(s: string, vars?: Record<string, string | number>): string {
    let out = dict[s] ?? s;
    if (vars) for (const k in vars) out = out.split(`{${k}}`).join(String(vars[k]));
    return out;
  }

  return <I18nCtx.Provider value={{ locale, rtl, t }}>{children}</I18nCtx.Provider>;
}

export const useT = () => useContext(I18nCtx);
